#!/usr/bin/env python3
"""Regenerate BACKLOG.html (and, on request, BACKLOG.md) from backlog.json.

INSTALL: replace every `[PROJECT_NAME]` in this file with the project's name,
and replace `AREA_LABEL` below with the project's own area vocabulary.

`backlog.json` is the canonical list; the views are generated from it and are
never edited by hand. They are regenerated by the pre-commit hook whenever the
JSON is staged, so a stale view cannot reach a commit — which is the only sense
in which "kept in sync" can be made to mean something.

**BACKLOG.html is the default view** (user's instruction, 2026-09-25): one row
per task, sortable by any column, filterable by priority, status, area and period-work fit, and
searchable across the title and the description. It carries the whole of
`backlog.json` inside it, so it is one self-contained file that opens from disk
with no server and no network. Open it in a browser.

**BACKLOG.md** is optional (`--md`): a document grouped by priority, for reading
in order or in a diff. If a repo already has a BACKLOG.md, it keeps being
regenerated so it cannot go stale.

It also **recomputes `metadata.total_tasks` and `metadata.next_id`** from the
tasks themselves and writes the correction back. Those fields were maintained by
hand and drifted; see `recompute_metadata`.

Standard library only. See 0_context/protocol/BACKLOG_PROTOCOL.md.

Usage:
    python3 scripts/render_backlog.py          # BACKLOG.html (+ BACKLOG.md if it exists)
    python3 scripts/render_backlog.py --md     # also create/refresh BACKLOG.md
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "0_context" / "protocol" / "backlog.json"
TARGET = REPO / "0_context" / "protocol" / "BACKLOG.md"
HTML_TARGET = REPO / "0_context" / "protocol" / "BACKLOG.html"

PRIORITY_ORDER = ["now", "mvp", "post_mvp", "someday"]
PRIORITY_LABEL = {
    "now": "Now — blocking or waiting on someone",
    "mvp": "MVP — needed before the project's first real use on real data",
    "post_mvp": "Post-MVP — wanted, scheduled after MVP",
    "someday": "Someday — good idea, no committed timeline",
}
STATUS_ICON = {
    "open": "⬜",
    "in_progress": "🔄",
    "done": "✅",
    "dropped": "🚫",
}
# `period_work`: whether Claude can do the task unsupervised during a period of
# work (Feature 8, the Period Work Protocol). Unset means not yet rated.
PERIOD_WORK_LABEL = {
    "yes": "yes — clear, verifiable, no user decisions expected",
    "maybe": "maybe — can progress alone, but likely stops at a judgment call",
    "no": "no — needs the user, external action, or sensitive judgment",
}

# Display names for the `area` values. REPLACE THESE with your project's own —
# they must match the vocabulary in BACKLOG_PROTOCOL.md. An area used in
# backlog.json but missing here still renders; it just shows its raw value.
AREA_LABEL = {
    "data": "Data",
    "analysis": "Analysis",
    "interface": "Interface",
    "schema": "Schema",
    "ops": "Operations",
    "docs": "Documentation",
    "protocol": "Protocol",
    "legal": "Legal",
}


def render(data: dict) -> str:
    tasks = data["tasks"]
    meta = data["metadata"]
    open_tasks = [t for t in tasks if t["status"] in ("open", "in_progress")]
    closed_tasks = [t for t in tasks if t["status"] in ("done", "dropped")]

    out: list[str] = []
    add = out.append

    add("# [PROJECT_NAME] — Backlog")
    add("")
    add("**GENERATED FILE — do not edit.** Regenerate with `python3 scripts/render_backlog.py`.")
    add("The canonical source is `0_context/protocol/backlog.json`.")
    add(f"Protocol: `{meta['protocol']}`. Last updated: **{meta['last_updated']}**.")
    add("")
    add(f"**{len(open_tasks)} open**, {len(closed_tasks)} closed, {len(tasks)} total.")
    add("")
    add("---")
    add("")

    for priority in PRIORITY_ORDER:
        group = [t for t in open_tasks if t["priority"] == priority]
        if not group:
            continue
        add(f"## {PRIORITY_LABEL[priority]}")
        add("")
        for t in sorted(group, key=lambda x: x["id"]):
            icon = STATUS_ICON.get(t["status"], "⬜")
            area = AREA_LABEL.get(t["area"], t["area"])
            add(f"### {icon} {t['id']} — {t['title']}")
            add("")
            period = t.get("period_work")
            period = f" · period work: {period}" if period else ""
            add(f"*{area} · raised {t['raised']} by {t['raised_by']}{period}*")
            add("")
            # `scale: epic` marks a task too large to pick up as written, which
            # must be broken into phases and subtasks before any of it is built
            # (from OpenQuali, 2026-09-23). Shown here rather than buried in the
            # JSON, because it has to be seen when somebody chooses what to work on.
            if t.get("scale") == "epic":
                add("> **EPIC — break into phases and subtasks before starting.** "
                    "Too large to pick up as written.")
                add("")
            add(t["description"])
            add("")
            if t.get("blocked_by"):
                add(f"**Blocked by:** {t['blocked_by']}")
                add("")
            refs = t.get("related") or []
            if refs:
                add(f"**Related:** {', '.join(refs)}")
                add("")
            add(f"<sub>Raised in `{t['raised_in']}`</sub>")
            add("")
        add("---")
        add("")

    if closed_tasks:
        add("## Closed")
        add("")
        add("| ID | Title | Status | Closed | Resolution |")
        add("|---|---|---|---|---|")
        for t in sorted(closed_tasks, key=lambda x: x["id"]):
            icon = STATUS_ICON.get(t["status"], "")
            res = (t.get("resolution") or "").replace("|", "\\|")
            add(f"| {t['id']} | {t['title']} | {icon} {t['status']} | {t.get('closed') or ''} | {res} |")
        add("")

    return "\n".join(out) + "\n"


HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>[PROJECT_NAME] — Backlog</title>
<style>
 :root {
   --bg:#0e1116; --surface:#171a20; --raised:#21252d; --ink:#dde3ec; --muted:#8c96a5;
   --line:#2a303a; --accent:#5f9ede; --warn:#e0a163; --ok:#6fae72; --danger:#b5502f;
   color-scheme: dark;
 }
 * { box-sizing:border-box; }
 body { margin:0; background:var(--bg); color:var(--ink);
        font:14px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif; }
 header { padding:1rem 1.25rem .6rem; border-bottom:1px solid var(--line); background:var(--surface); }
 h1 { margin:0 0 .2rem; font-size:1.05rem; letter-spacing:.01em; }
 .meta { color:var(--muted); font-size:12px; }
 .controls { display:flex; flex-wrap:wrap; gap:.5rem; padding:.7rem 1.25rem;
             background:var(--surface); border-bottom:1px solid var(--line); position:sticky; top:0; z-index:5; }
 .controls input, .controls select {
   background:#0f1217; color:var(--ink); border:1px solid var(--line);
   border-radius:5px; padding:.3rem .5rem; font:inherit; }
 .controls input[type=search] { min-width:20rem; flex:1; }
 .count { margin-left:auto; color:var(--muted); font-size:12px; align-self:center; }
 table { border-collapse:collapse; width:100%; font-size:13px; }
 th, td { text-align:left; vertical-align:top; padding:.45rem .6rem;
          border-bottom:1px solid var(--line); }
 th { position:sticky; top:3.1rem; background:var(--raised); color:var(--muted);
      font-size:11px; text-transform:uppercase; letter-spacing:.05em; cursor:pointer; user-select:none;
      white-space:nowrap; z-index:4; }
 th .arrow { opacity:.45; font-size:9px; margin-left:.25rem; }
 tbody tr:hover { background:rgba(255,255,255,.03); }
 td.id { font-family:ui-monospace,Menlo,Consolas,monospace; white-space:nowrap; color:var(--muted); }
 td.title { font-weight:550; }
 .pill { display:inline-block; padding:.05rem .45rem; border-radius:999px;
         font-size:11px; border:1px solid var(--line); white-space:nowrap; }
 .p-mvp { color:var(--warn); border-color:#4b3722; background:#33261a; }
 .p-now { color:#fff; background:var(--danger); border-color:var(--danger); }
 .p-post_mvp, .p-someday { color:var(--muted); }
 .p-epic { color:#c9a6ff; border-color:#3d2f55; background:#241a33; }
 .pw-yes { color:var(--ok); } .pw-maybe { color:var(--warn); } .pw-no, .pw-unrated { color:var(--muted); }
 .s-done { color:var(--ok); } .s-in_progress { color:var(--accent); }
 .s-dropped { color:var(--muted); text-decoration:line-through; }
 tr.done td.title { color:var(--muted); font-weight:400; }
 .why { color:var(--muted); font-size:12px; margin-top:.2rem; max-width:62rem; }
 .why b { color:var(--ink); font-weight:600; }
 .none { padding:2rem 1.25rem; color:var(--muted); }
</style></head><body>
<header>
  <h1>[PROJECT_NAME] — Backlog</h1>
  <div class="meta">__META__</div>
</header>
<div class="controls">
  <input type="search" id="q" placeholder="Search titles, descriptions and resolutions…">
  <select id="priority"><option value="">Any priority</option>__PRIORITIES__</select>
  <select id="status"><option value="">Any status</option>__STATUSES__</select>
  <select id="area"><option value="">Any area</option>__AREAS__</select>
  <select id="period" title="Suitable for unsupervised period work?"><option value="">Any period-work fit</option>
    <option value="yes">Period work: yes</option><option value="maybe">Period work: maybe</option>
    <option value="no">Period work: no</option><option value="unrated">Period work: unrated</option></select>
  <select id="detail">
    <option value="open">Show why (open tasks)</option>
    <option value="all">Show why (everything)</option>
    <option value="none">Titles only</option>
  </select>
  <span class="count" id="count"></span>
</div>
<table>
  <thead><tr>
    <th data-key="id">Task<span class="arrow"></span></th>
    <th data-key="priority">Priority<span class="arrow"></span></th>
    <th data-key="status">Status<span class="arrow"></span></th>
    <th data-key="area">Area<span class="arrow"></span></th>
    <th data-key="period_work" title="Suitable for unsupervised period work?">Period<span class="arrow"></span></th>
    <th data-key="title">Title<span class="arrow"></span></th>
    <th data-key="raised">Raised<span class="arrow"></span></th>
  </tr></thead>
  <tbody id="rows"></tbody>
</table>
<p class="none" id="empty" hidden>Nothing matches.</p>
<script id="data" type="application/json">__DATA__</script>
<script>
const TASKS = JSON.parse(document.getElementById('data').textContent);
const PRIORITY_RANK = { now: 0, mvp: 1, post_mvp: 2, someday: 3 };
const STATUS_RANK = { in_progress: 0, open: 1, done: 2, dropped: 3 };
const PERIOD_RANK = { yes: 0, maybe: 1, no: 2 };
const period = (task) => task.period_work || 'unrated';
let sort = { key: 'priority', dir: 1 };

// Coerced, not assumed: `blocked_by` is a string on some tasks and a list on
// others, and one non-string killed the whole first render.
const esc = (s) => (Array.isArray(s) ? s.join(', ') : (s ?? ''))
  .toString().replace(/[&<>]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;' }[c]));

function key(task) {
  if (sort.key === 'priority') return [PRIORITY_RANK[task.priority] ?? 9, STATUS_RANK[task.status] ?? 9, task.id];
  if (sort.key === 'status') return [STATUS_RANK[task.status] ?? 9, PRIORITY_RANK[task.priority] ?? 9, task.id];
  if (sort.key === 'period_work') return [PERIOD_RANK[task.period_work] ?? 3, PRIORITY_RANK[task.priority] ?? 9, task.id];
  return [String(task[sort.key] ?? ''), task.id];
}

function draw() {
  const q = document.getElementById('q').value.trim().toLowerCase();
  const want = (id) => document.getElementById(id).value;
  const detail = want('detail');
  const rows = TASKS.filter((t) =>
    (!want('priority') || t.priority === want('priority')) &&
    (!want('status') || t.status === want('status')) &&
    (!want('area') || t.area === want('area')) &&
    (!want('period') || period(t) === want('period')) &&
    (!q || [t.id, t.title, t.description, t.resolution].join(' ').toLowerCase().includes(q))
  ).sort((a, b) => {
    const ka = key(a), kb = key(b);
    for (let i = 0; i < ka.length; i += 1) {
      if (ka[i] < kb[i]) return -sort.dir;
      if (ka[i] > kb[i]) return sort.dir;
    }
    return 0;
  });

  document.getElementById('rows').innerHTML = rows.map((t) => {
    const show = detail === 'all' || (detail === 'open' && t.status !== 'done' && t.status !== 'dropped');
    const why = show
      ? `<div class="why">${esc(t.description)}${t.resolution ? `<br><b>Resolved:</b> ${esc(t.resolution)}` : ''}${
          t.blocked_by ? `<br><b>Blocked by:</b> ${esc(t.blocked_by)}` : ''}</div>`
      : '';
    return `<tr class="${t.status}">
      <td class="id">${esc(t.id)}</td>
      <td><span class="pill p-${t.priority}">${esc(t.priority)}</span>${t.scale === 'epic' ? ' <span class="pill p-epic">epic</span>' : ''}</td>
      <td class="s-${t.status}">${esc(t.status)}</td>
      <td>${esc(t.area)}</td>
      <td class="pw-${period(t)}">${esc(period(t))}</td>
      <td class="title">${esc(t.title)}${why}</td>
      <td class="id">${esc(t.raised)}</td>
    </tr>`;
  }).join('');
  document.getElementById('empty').hidden = rows.length > 0;
  const openCount = rows.filter((t) => t.status === 'open' || t.status === 'in_progress').length;
  document.getElementById('count').textContent =
    `${rows.length} shown · ${openCount} open`;
  document.querySelectorAll('th').forEach((th) => {
    th.querySelector('.arrow').textContent =
      th.dataset.key === sort.key ? (sort.dir === 1 ? '\u25b2' : '\u25bc') : '\u21c5';
  });
}

document.querySelectorAll('th').forEach((th) => {
  th.onclick = () => {
    if (sort.key === th.dataset.key) sort.dir *= -1;
    else sort = { key: th.dataset.key, dir: 1 };
    draw();
  };
});
['q', 'priority', 'status', 'area', 'period', 'detail'].forEach((id) =>
  document.getElementById(id).addEventListener('input', draw));
draw();
</script>
</body></html>
"""


def render_html(data: dict) -> str:
    """One self-contained page: the whole backlog, sortable and filterable.

    The JSON is embedded rather than fetched, because this file is opened from
    disk and a browser refuses to fetch a local file from another local file. It
    is regenerated whenever `backlog.json` is committed, so the copy is never the
    stale one — see the pre-commit hook.
    """
    tasks = data["tasks"]
    meta = data["metadata"]
    counts = {}
    for task in tasks:
        counts[task["status"]] = counts.get(task["status"], 0) + 1
    open_now = counts.get("open", 0) + counts.get("in_progress", 0)
    mvp_open = sum(1 for t in tasks
                   if t["priority"] == "mvp" and t["status"] in ("open", "in_progress"))

    def options(values, labels=None):
        return "".join(
            f'<option value="{v}">{(labels or {}).get(v, v)}</option>'
            for v in values
        )

    priorities = [p for p in PRIORITY_ORDER if any(t["priority"] == p for t in tasks)]
    statuses = sorted({t["status"] for t in tasks})
    areas = sorted({t["area"] for t in tasks})

    summary = (
        f"{len(tasks)} tasks · {open_now} open · {mvp_open} open at MVP priority · "
        f"generated from backlog.json, last updated {meta.get('last_updated', '?')} · "
        f"never edit this file"
    )
    return (HTML_TEMPLATE
            .replace("__META__", summary)
            .replace("__PRIORITIES__", options(priorities))
            .replace("__STATUSES__", options(statuses))
            .replace("__AREAS__", options(areas, AREA_LABEL))
            .replace("__DATA__", json.dumps(tasks, ensure_ascii=False)))


def recompute_metadata(data: dict) -> list[str]:
    """Derive `total_tasks` and `next_id` from the tasks themselves.

    They were maintained by hand and drifted: on 2026-09-10 the file said 244
    tasks and `TASK-245` next while actually holding 258. A stored count that
    disagrees with the array is worse than no count, because the next id is read
    from it — and reusing an id silently reattributes work to a task somebody
    else has already referred to.

    So nothing trusts the stored values: they are recomputed here and written
    back, and the protocol tells the assistant to take the next id from the array
    rather than from the field. Returns a list of the corrections made, so a
    drift is reported rather than fixed in silence.
    """
    meta = data["metadata"]
    tasks = data["tasks"]
    corrections: list[str] = []

    total = len(tasks)
    if meta.get("total_tasks") != total:
        corrections.append(f"total_tasks {meta.get('total_tasks')} → {total}")
        meta["total_tasks"] = total

    # The highest id ever used, plus one. Highest rather than count, because ids
    # are never reused and a dropped task still holds its number.
    highest = 0
    for task in tasks:
        try:
            highest = max(highest, int(str(task["id"]).split("-")[-1]))
        except (ValueError, KeyError):
            continue
    next_id = f"TASK-{highest + 1:03d}"
    if meta.get("next_id") != next_id:
        corrections.append(f"next_id {meta.get('next_id')} → {next_id}")
        meta["next_id"] = next_id

    return corrections


def main() -> int:
    if not SOURCE.exists():
        print(f"error: {SOURCE} not found", file=sys.stderr)
        return 1
    data = json.loads(SOURCE.read_text(encoding="utf-8"))

    ids = [t["id"] for t in data["tasks"]]
    if len(ids) != len(set(ids)):
        print("error: duplicate task IDs in backlog.json", file=sys.stderr)
        return 1

    corrections = recompute_metadata(data)
    if corrections:
        SOURCE.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                          encoding="utf-8")
        for line in corrections:
            print(f"corrected metadata: {line}")

    HTML_TARGET.write_text(render_html(data), encoding="utf-8")
    written = [HTML_TARGET]
    if "--md" in sys.argv[1:] or TARGET.exists():
        TARGET.write_text(render(data), encoding="utf-8")
        written.append(TARGET)
    print(f"wrote {' and '.join(str(p.relative_to(REPO)) for p in written)} "
          f"({len(data['tasks'])} tasks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
